# Generated by Django 5.1.5 on 2025-02-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_pokemon_title_en_pokemon_title_jp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='old_evolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon'),
        ),
    ]
