# Generated by Django 5.1.5 on 2025-02-05 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_pokemon_old_evolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='old_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon'),
        ),
    ]
